name: Paper-Kotlin-Template
version: 1.0.0
main: dev.incognitojam.template.PluginTemplate
api-version: '1.20'
authors: [ incognitojam ]
description: Paper Plugin Template written in Kotlin.
website: https://github.com/incognitojam
